services:
  api:
    build:
      context: ./packages/api
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - JWT_SECRET=e457bd37613a8fa736ec0234173dd22c7871602cc9368408aba4fa062fed8771
      - WHATSAPP_CALLBACK_VERIFY_CODE=e91b89f6a906d6cc357565227ee4594326130cdaeab7d22c87e79d3f9dc7e537
      - WHATSAPP_API_TOKEN=EAAC1E0iNBFsBSLrsZABHQZAl7OTDUdoqQELIFsrJIGwBigOZCPHR6LBHTcTBVRDOQ2ZARZBXk31iGNqtS7rZBeWb3mb2N6Tn5ZCZAwTzz2G2omyT40LPU9B3SrwjMcuViBpZCtQfH1ZCcZCC8iXsGGdO3YayDajp63vsCb0HPFU1sCGqQyR3MOUZCtoO4fg7kVOjKQZDZD
      - REDIS_HOST=127.0.0.1
      - REDIS_PORT=6379
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Root#1234
      - MYSQL_DATABASE=merapihost
      - FIREBASE_PROJECT_ID=merapihost-56b89
      - FIREBASE_CLIENT_EMAIL=firebase-adminsdk-fbsvc@merapihost-56b89.iam.gserviceaccount.com
      - FIREBASE_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDESDXpyMBNBOfi\nrxQVLRw5CVOzvQSKoTo+wJmCbDVjBTaWOf0kruVaQLxJhlJthaf37RafVZFqfYll\nWXsqImjOIwcjmZcyPmZ4os38lDaEMFwT93HyTWbrypnryucVhP+wGKdIN6odysr/\nK4ZOhvEpSmvUWdpihNHjO7C14ZvTxhLV/zW1+r7BBz2fOALGogQwSSee7rlOqOCN\nnlUYrO8ZtC4ZpP1I2oyIQBKgaltt8PTJ5UGpDB+mO4NjnwXIXCK4FInsZsjx7/z/\nSnfxGK8kQf1W0HkXSSe4oH6EGD45dI9SbZcDkfxpM7n+QOEkzW8Z88UMEE7e6Lz9\nZs5wPoG9AgMBAAECggEACzH7MTxsC3iOKVXHFXYfN/maNpQ/YBDWG6Isn03Atcck\nV+ky0RbQqhcrJh5tMSYAcJmrQqdExggnAArchYi05Z0F2Tf3cbwxaAwRJ6jkeyGu\n/syMST+08Rn7MYG/MHEHjGm7kNjr8QsSDP/Uh0IXGz3NbK07UYc12XocGCOoGaoG\n69NDfNAiZnCMC1JrWampGPZ6f3aJg7Y14yFwSn1TRIMa/U4HblhFW77XbIWaaUk/\nTr5ZpQMznMdDWwxt/ZgV7ktlyk57eKDN+lEQrPeOvd77OEVPV9OJzAGogBTERaQC\n6cyUgAAEter0vzv3zrqlyDGS47JyBcI8Q1mRZbiUQQKBgQDqwGnv3J9lJfa46LPr\nEXzRbcv7e7kf1psAPz6mqslwHpLmblJgrxlOKQKX3fLK8+AmLjp9ILcfM+ffiV5n\n9+ufaYM4yL/SO+rbC4CRKbP73AQurwFssTOOloeNfXVXo/vhW6iNDB2GBZHWXaeF\nGDqtT5tG0o0RJRShTdSN/U1LlQKBgQDWDGSx6hfge8Umn1YGK2tppIVteh2QADkM\nuubGZ3ouc+nXL/p9Ek9wxsbrQcfEDeGl7Zl7kf/DOL0ZWlXpseO9FTj25SypyztU\n90dMrv8WWhEUbN/sIfL4XBLhSsLtiqGYm/3/p22QsS5gZT3KiZjivjMGj7af66sm\n8iathvETiQKBgBXOmgi2LfhvdmPm+g+0KCwsTu6lp6TVgsCbH27MHrpTnMHbLbvd\niDRCiwMgkxVXYlMpqDVHfLthTwDs+eAen7zHSHFV9LvK5R5EC0Vw4k9bOOg9SZyX\nOXrdcOor5WKm0Rc2NIolvfhdPBb1zEII5iqDYqFJneEh2LDDUiN+jFehAoGBAJ3c\nug71BPMMlVRswvb94tQhAD7DhzYC1BBtb3H4MwY7esS3n9fKP0h/cYlkFD6ltju3\nxjB6dtS17dDa7O3TwpBbLI36azw2pOV/EdieX4dOmbYkrejrCNTeoxYBG04xpgh1\nU5jPFGFYK0nwoOfVHypq+Brottmu56VrhdcI5JdxAoGAI/toipSz8uCBFEsVjNNb\nbdfM8HMHciELt3NHR3t/0m6hdJlN2Ef+5ydmsv8FR56KVH0mOgYyQS7xUyWMXrwc\n/eatt75aEu39pNkywmhSFcEXacvyvuJOt+REeOzvTZf2kTyCbxbEJqI7FgazI5YU\nUZFOz0nfjXIjgnmB++wo3Yk=\n-----END PRIVATE KEY-----\n
      - S3_ACCESS_KEY_ID=4V31SDACYP4MATJ130JN
      - S3_SECRET_ACCESS_KEY=aIi0t8OxyKnIuDwcCeFBu5p1tQ76OIpkh2B7xFVH
      - S3_BUCKET_NAME=merapihost
      - S3_ENDPOINT=is3.cloudhost.id
    volumes:
      - ./packages/api:/usr/local/merapihost/api
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  serve:
    build: 
      context: ./packages/serve
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./packages/serve:/usr/local/merapihost/serve
    extra_hosts:
      - "host.docker.internal:host-gateway"
    